import type { IconType } from 'react-icons';
import {
  LuArchive,
  LuBanknote,
  LuClipboardList,
  LuLandmark,
  LuCalendarPlus,
  LuLayoutDashboard,
  LuLogOut,
  LuMapPinned,
  LuMessageSquare,
  LuMessageSquareWarning,
  LuBell,
  LuSend,
  LuLifeBuoy,
  LuImages,
  LuShield,
  LuBookOpen,
  LuPackage,
  LuPanelLeftClose,
  LuPanelLeftOpen,
  LuRepeat,
  LuTruck,
  LuUserCog,
  LuUsers,
  LuWallet,
  LuHandCoins,
} from 'react-icons/lu';
import type { SidebarTab } from './routes';

export const TAB_ICONS: Record<SidebarTab, IconType> = {
  overview: LuLayoutDashboard,
  customers: LuUsers,
  subscriptions: LuRepeat,
  tasks: LuClipboardList,
  complaints: LuMessageSquareWarning,
  tickets: LuMessageSquare,
  notifications: LuBell,
  'send-notification': LuSend,
  support: LuLifeBuoy,
  gallery: LuImages,
  privacy: LuShield,
  instructions: LuBookOpen,
  managers: LuUserCog,
  drivers: LuTruck,
  plans: LuPackage,
  bins: LuArchive,
  locations: LuMapPinned,
  payments: LuBanknote,
  'bank-account': LuLandmark,
  'additional-collection': LuCalendarPlus,
  'deposit-requests': LuWallet,
  'cash-topups': LuHandCoins,
};

export { LuLogOut, LuPanelLeftClose, LuPanelLeftOpen };
